### ISSUE TITLE
Server Spamming Error

### ISSUE THREAD

**Issue by Rythiq** [McJty/McJtyLib#126]
![Screenshot 2020-11-03 134719](https://user-images.githubusercontent.com/73889610/97987161-1d352e80-1ddb-11eb-93f4-198f4090368a.png)
I have an ATM6 v.1.1.9b server set up und suddenly (not after an update) after a restart, the server spammst following message once loaded up:
←[m←[1;31m[13:45:07] [Server thread/ERROR] [mcjtylib/]: The mob spawn amounts list for mob minecraft:cow is missing!
its really annoying bcs this message shows up once/tick and makes the log als well as the console unusable... anyone got a fix for that?
version is: mcjtylib-1.16-5.0.11

**Comment by McJty** [comment]
This has been fixed in a recent update to McJtyLib

**Comment by Rythiq** [comment]
The problem is, that i just updatet to Version 5.0.12 of your mod and I still have the same issue
so NO this has NOT BEEN FIXED im sorry...

**Comment by McJty** [comment]
Oops. I meant RFTools Utility. You have to update that. In addition it might be needed to manually remove the rftools utility config. Not 100% sure about that
